### ISSUE TITLE
Unable to use Remove-Index (without explicit name) for Add-Index created with -Include

### ISSUE THREAD

**Issue by pnstickne** [pshdo/Rivet#42]
Observed in Rivet 0.12:

Using `Add-Index -TableName Quxx -Columns Foo -Include Bar` results in an index with the name `IX_Quxx_Foo_wInc`.

However, `Remove-Index -TableName Quxx -Columns Foo` cannot be used to remove this index because that resolves to `IX_Quxx_Foo` without the "wInc" suffix and there is no `-Include` option for the `Remove-Index` command.

The work-about is to use `Remove-Index -TableName Quxx -Name IX_Quxx_Foo_wInc` to manually/explicitly delete the index by name.

Some possible approaches to increase Add-Index/Remove-Index consistency:

- Remove-Index checks for a "wInc"-named index, and removes it if such exists, perhaps raising an error on ambiguity.
- Remove-Index accepts `-Include string[]` like Add-Index, to signify the name to resolves to "wInc".
- Remove-Index accepts `-WithInclude` or similar flag, to signify the name to resolves to "wInc".

**Comment by splatteredbits** [comment]
Rivet's automatic object naming on indexes, constraints, etc., is deprecated and will be removed before or when Rivet reaches version 1.0.
